version: '3.5' #docker

services:
  db_auth:
    container_name: db_auth
    ports:
      - ${db_port_auth}:${db_port_auth} #opened ports for the container
    environment: #value that sends to our DB
      POSTGRES_USER: ${db_user_auth}
      POSTGRES_PASSWORD: ${db_password_auth}
    image: postgres:13.12 #the image that uses the container from hub.docker.com/_/postgres/tags is a prepared database in the container
    command: # command to set the port we want
      - 'postgres'
      - '-c'
      - 'port=${db_port_auth}'
    volumes: # volume in order to save data when restarting the container
      - db_auth_vol:/var/lib/postgres/data/ # docker writes from /var/lib/postgres/data/ to db_auth_vol
    networks:
      - server_net

# indicate which volumes and networks we will use
volumes:
    db_auth_vol: {}
networks:
    server_net:
      driver: bridge